name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  tf_plan:
    runs-on: ubuntu-latest
    name: Plan terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::674890471878:role/GitHubActionsRole

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: ./infra
          backend_config_file: ./infra/dev/backend.config
          var_file: ./infra/dev/vars/dev.tfvars

  apply-plan:
    runs-on: ubuntu-latest
    needs: tf_plan
    name: Apply terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::674890471878:role/GitHubActionsRole

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./infra
          backend_config_file: ./infra/dev/backend.config
          var_file: ./infra/dev/vars/dev.tfvars
          auto-approve: true