name: Build and Push to ECR

on:
  push:
    branches:
      - feature/initial-module-creation

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    env:
      ECR_REPO: interview-app-project-repo

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          region: us-east-1
          role-to-assume: my-github-actions-role
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPO }}
          IMAGE_TAG: ${{ CI_COMMIT_SHORT_SHA }}
        run: |
          cd app
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: examples/
        recursive: true
        recursive-path: modules
        output-file: README.md
        output-method: inject
        git-push: "true"